spring:
  application:
    name: bus-hub-basic

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bh_basic
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhm-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: true
    mixed: true
    out-of-order: true
    table: schema_version


#------------------------------------
# Server settings
#------------------------------------

server:
  port: 8500
  servlet:
    context-path: /api
